# Generated by Django 5.1.1 on 2024-10-31 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecopuntosapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('descripction', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
            ],
        ),
    ]
