# Generated by Django 5.1.1 on 2024-12-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecopuntosapp', '0004_alter_accounts_moderator'),
    ]

    operations = [
        migrations.CreateModel(
            name='request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reqname', models.CharField(max_length=20)),
                ('reqemail', models.CharField(max_length=30)),
                ('typereq', models.IntegerField(choices=[(0, 'objeto'), (1, 'lugar')])),
            ],
        ),
        migrations.RenameField(
            model_name='objects',
            old_name='name',
            new_name='objname',
        ),
    ]
