# Generated by Django 5.1.1 on 2024-12-03 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecopuntosapp', '0005_request_rename_name_objects_objname'),
    ]

    operations = [
        migrations.CreateModel(
            name='userrequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reqname', models.CharField(max_length=20)),
                ('reqemail', models.CharField(max_length=30)),
                ('typereq', models.IntegerField(choices=[(0, 'objeto'), (1, 'lugar')])),
                ('requestext', models.TextField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='request',
        ),
    ]
