# Generated by Django 5.1.1 on 2024-12-03 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecopuntosapp', '0006_userrequest_delete_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='useraccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=25)),
                ('trust', models.IntegerField(default=0)),
                ('moderator', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Accounts',
        ),
    ]
